services:
  - type: web
    name: whisperr
    env: ruby
    region: oregon
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: whisperr_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

databases:
  - name: whisperr_db
    region: oregon
